### ISSUE TITLE
JsonSetForm not compiling

### ISSUE THREAD

**Issue by Behrtron** [surilindur/objson#1]
Tried with player ref
Tried with getcrosshairref

Oblivion Script does not compile
obse v22
Cs 1.2
Latest oblivion patch

**Comment by Behrtron** [comment]
Error:
Param type '32776' unimplemented in Script compiler::standardcomple

**Comment by Behrtron** [comment]
My script that isn't working:

 if IsControlPressed 5
    set crossref to getcrosshairref
    if crossref.isactivatable
        JsonSetForm "PlayerUpdate.json"  "Activated.refid" crossref
     endif
endif

**Comment by Behrtron** [comment]
Other calls compile and work like Int or string

**Comment by surilindur** [comment]
This will most likely definitely not compile, and it if does, it will probably not work. Sorry. :sweat: I started restructuring this at some point but never finished it. It has been made trickier by not having Windows installed anywhere at the moment, but I am hoping to finish the restructuring (will be more of a rewrite I guess) later this year when I have more time, hopefully in December.

**Comment by surilindur** [comment]
Oh you mean scripts within the CS do not compile. I will need to look into that in December, as well. When I made this plugin, it was for OBSE v21 if I remember correctly. Maybe something has changed.

**Comment by Behrtron** [comment]
Thanks for the info! I also tried with obse 21 and got the same error, I appreciate the response though, I'm working on an online mod and this plugin was immensely helpful in allowing me to extract some player info.

Here's my mods progress
https://youtu.be/jO3Ox3HC7qg?si=1op2P__uRSyirY8K

**Comment by surilindur** [comment]
Oh, I did not know someone else is actually using this. Good luck with your project! My plan is to get back to modding Oblivion soon, as well, since I also have some projects that I want to finish. Real life has unfortunately taken a lot of time recently. It looks like I will have time in December, so I will start by finishing the rewrite on this one.

Are you compiling your script via the Construction Set Extender UI? And is that the full error that you get? A quick search for that error message or parts of it did not produce anything useful, and it should work on OBSE 21. This is confusing. :thinking:

**Comment by Behrtron** [comment]
I will experiment with v20 and v21 again to see if I did something wrong first time around. If same error I'll compile against it in my solution and try to debug the issue too! I totally get it I'm a corporate engineer myself so it's hard to find time haha. Yes this solution is much better for me than forcing people to include pluggy haha

**Comment by surilindur** [comment]
The last time I compiled this thing was years ago, and if I remember correctly it does not compile in its current state. I also wanted to restructure the code a bit, it is not a lot but it is really ugly from back when I had no idea how to work with C++. :grimacing: It feels to me like the best solution would  be to figure out why the script does not compile.

One thing about unimplemented parameter types I was able to find was the OBSE array variable thing in OBSE code, apparently it should trigger a warning when saving scripts without some 'compiler override'. But if you use the Construction Set Extender from shadeMe (and not the normal CS without it) then that should already be handled, I guess.

I cannot even remember if I used arrays in this one. :sweat_smile:

**Comment by Behrtron** [comment]
Ah that is definitely the issue,  just loading obse_loader -editor with no extender from shademe, thank you!

**Comment by surilindur** [comment]
But I do not know if CSE does something different with compiling scripts. I just never tried to use the CS without CSE.

I assume it should not differ in any way?

**Comment by Behrtron** [comment]
Yeah, I'll see what happens if I run with cse cause that is definitely a big difference between our environments

**Comment by Behrtron** [comment]
very strange, so i got the CSE up and running, i love it already and cant believe ive been modding all these years without it lol. how ever now im getting an error with this code but its not giving me any error message, it just says it failed to compile. setstring and setint both work fine

**Comment by Behrtron** [comment]
ah wait found the erro log, yes its the same erro with obse v21 and cse:

[CS]	Param type '32776' unimplemented in ScriptCompiler::StandardCompile.

**Comment by Behrtron** [comment]
oh man you were so right... i just needed to use the _ for compiler override.. it works!! thank you again for you help! oblivion online lives on...

**Comment by Behrtron** [comment]
the book my player activated!! "FormRefID": "000A6A0E:Oblivion.esm", thanks again for the help man this is exciting

**Comment by surilindur** [comment]
Awesome to hear. I already forgot the underscore thing. Maybe I should get back to modding soon or else I will forget everything. :sweat_smile:

I hope you are not using the JSON thing for realtime communication between Oblivion and a web server, because I designed it more for saving and reloading configuration data for mods as an alternative to INI files. It will also probably trash the disk if you use it for that. If you need to move data between the game and something on the web, I would suggest looking into [the official example plugin](https://github.com/llde/xOBSE/tree/master/obse_plugin_example) and writing your own one to communicate with a server.

Good luck with your project, though! :slightly_smiling_face:

**Comment by Behrtron** [comment]
Thanks! Currently using Tcp and Raknet udp for various transmission of data, just using json periodically obtain player info
